export const NEXT_PUBLIC_BACKGROUND_OPTIONS = process.env.NEXT_PUBLIC_BACKGROUND_OPTIONS;
export const NEXT_PUBLIC_BODY_OPTIONS = process.env.NEXT_PUBLIC_BODY_OPTIONS;
export const NEXT_PUBLIC_MOUTH_OPTIONS = process.env.NEXT_PUBLIC_MOUTH_OPTIONS;
export const NEXT_PUBLIC_TUSK_OPTIONS = process.env.NEXT_PUBLIC_TUSK_OPTIONS;
export const NEXT_PUBLIC_EYE_OPTIONS = process.env.NEXT_PUBLIC_EYE_OPTIONS;
export const NEXT_PUBLIC_GLASSES_OPTIONS = process.env.NEXT_PUBLIC_GLASSES_OPTIONS;
export const NEXT_PUBLIC_HAIR_OPTIONS = process.env.NEXT_PUBLIC_HAIR_OPTIONS;
export const NEXT_PUBLIC_ENERGY_INCREASE =
  process.env.NEXT_PUBLIC_ENERGY_INCREASE;
export const NEXT_PUBLIC_ENERGY_DECREASE =
  process.env.NEXT_PUBLIC_ENERGY_DECREASE;
export const NEXT_PUBLIC_ENERGY_CAP = process.env.NEXT_PUBLIC_ENERGY_CAP;
